1 die or2
mattolbert/ShutTheBox pull request #4
Opened 2024-03-21 13:26 UTC by mattolbert

hows this?

2024-03-21 15:20 UTC, mcdaly requested changes
Overall, looks good! Coupe minor code cleanup and edge cases that should be addressed

2024-03-21 15:20 UTC, mcdaly commented on ShutTheBox.py
> +  print("You won! You shut the box!") #i did shut the box once but this didn't appear so I need to find a way to troubleshoot that
Interesting. As a great Shut-the-box player, I was able to hit this!
One thought on how to troubleshoot this is to make so the list of tiles to knock down only starts with a couple numbers instead of 1-9 so it is much easier to win 
`nums = list(range(1, 4))`

2024-03-21 15:20 UTC, mcdaly commented on ShutTheBox.py
> +  else: #i understand that this is not super elegant, I do want to try to simplify it, prob no need to have the same block twice in a row here
Sometimes, it needs to be done...

But a better solution would be to create a function that is called from these 3 different spots such as the following:

```
def roll_die(num_dice):
    if num_dice == 1:
        return random.randint(1, 6)
    elif num_dice == 2:
      die1 = random.randint(1, 6)
      die2 = random.randint(1, 6)
      return die1 + die2
```

2024-03-21 15:20 UTC, mcdaly commented on ShutTheBox.py
> +  if rollvalue == 8 or rollvalue == 11:
Update this to be `rollvalue in [8, 11]`
Using the list notation simplifies the code and makes it easier for adding additional numbers in the future (if needed)

2024-03-21 15:20 UTC, mcdaly commented on ShutTheBox.py
> +    print("You rolled an " + str(rollvalue))
Can you update these two lines to f-string format? Good luck!

2024-03-21 15:20 UTC, mcdaly commented on ShutTheBox.py
> +          if_valid = True
This logic is very close but doesn't work in all cases. Essentially it breaks if the user provides more than 1 number where one number is an available number and the other is a number that has already been knocked down
 
Example:
Tiles = [1, 2, 3, 6]
rollvalue = 7
choicelist = [3, 4] (entered by me)

Expected result is that it asks me to pick the numbers again and no tiles are removed.
Unfortunately, it removes the 3, prints out "Try again" for the 4 but still proceeds to roll again and move onto the next turn

2024-03-21 15:20 UTC, mcdaly commented on ShutTheBox.py
> +  if 7 not in nums and 8 not in nums and 9 not in nums:
Hmmm... there is a better way to do this instead of writing out each statement separately here.
Are you familiar with list comprehension? If so, try doing this with a binary check for each [7, 8, 9] value in a list comprehensions and then use the `all()` function to wrap it.
There may or may not be enough detail here for you to do this so try it out and let me know if you get stuck

2024-03-22 14:43 UTC, mattolbert commented on ShutTheBox.py
> +  print("You won! You shut the box!") #i did shut the box once but this didn't appear so I need to find a way to troubleshoot that
yeah this is working fine.

2024-03-22 15:08 UTC, mattolbert commented on ShutTheBox.py
> +    print("You rolled an " + str(rollvalue))
I'm guessing this would just be to re-write this print line as
print(f"You rolled an {rollvalue}")
no? if so, what's the advantage of this vs. what I wrote initially? if i'm misunderstanding the note here, let me know

2024-03-22 15:41 UTC, mcdaly commented on ShutTheBox.py
> +    print("You rolled an " + str(rollvalue))
No advantage in this case other than getting familiar with f-string which will be more versatile and cleaner in the future

2024-03-22 16:00 UTC, mattolbert commented on ShutTheBox.py
> +          if_valid = True
this is what i'm currently working on that I screwed up, FYI

2024-03-22 19:08 UTC, mattolbert commented on ShutTheBox.py
> +  if 7 not in nums and 8 not in nums and 9 not in nums:
forgot about this comment but I'll plan to get back to it

2024-03-23 01:08 UTC, mcdaly approved these changes

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
> +  if num_dice == '1':
Why the change to the strings? These should stay as ints unless there is a good reason for them to be strings

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
> +def has_duplicates(seq):#i built this because I accidentally typed "1, 1" in as user input and it did all sort of weirdness, I think this fixed it
Nice!

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
> +    rollvalue = roll_die('2')
back to int!

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
> +      intlist = [int(i) for i in choicelist]#can this and the line above it all happen at once?
Yes it can! Just put `int(i.strip())` so the choicelist is just a list of ints. This does require the user to only enter numbers (no letters or empty strings) but I think that is a fine assumption for this code.

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
> +      choicemath = sum(intlist)
Nice!

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
> +          break
I am seeing when I enter a double number that no numbers are put down but the dice are rolled again. This should not be the case.
I believe some confusion is around the `break` statement. The `break` statement terminates the current `for` or `while` loop being executed. In this case, this `break` statement is in the `while if_valid` so it is breaking out of the user input check and jumping to the next roll

2024-03-23 01:08 UTC, mcdaly commented on ShutTheBox.py
>        else:
Code is working well (except for the duplicate comment)!

This could be easier to follow if the print statement was next to the if statement. Here is a potential way to update this code block to simplify all the nested if statements

```   
      if choicemath != rollvalue:
        print("Your choice doesn't match the roll value")
      elif has_duplicates(intlist) == True:
        print("You can't put the same number down twice")
        break
      else:
        # Ensure all requested tiles are still up
        any_nums_down_already = any(i not in nums for i in intlist)
        if any_nums_down_already:
            print("Your number choice has already been put down")
        else:
          # Good inputs. Knock down tiles
          for i in intlist:
            nums.remove(i)
          if_valid = True
```

2024-03-23 15:37 UTC, mattolbert commented on ShutTheBox.py
> +      intlist = [int(i) for i in choicelist]#can this and the line above it all happen at once?
thanks!

2024-03-23 15:46 UTC, mattolbert commented on ShutTheBox.py
>        else:
this makes total sense. looking at mine, since I sort of was adding these exceptions and error messages as I went along, they ended up being sort of cobbled together. Had I thought about them all at the beginning, I mightve thought to streamline them together like this. good feedback.

2024-03-23 15:49 UTC, mattolbert commented on ShutTheBox.py
> +  if 7 not in nums and 8 not in nums and 9 not in nums:
honestly I'm still not really getting this, but I'd like to. can you explain a bit more? list comprehension is something I'm still struggling to get my head around.

2024-03-23 16:36 UTC, merged

2024-03-23 17:53 UTC, mcdaly commented on ShutTheBox.py
> +  if 7 not in nums and 8 not in nums and 9 not in nums:
You can think of list comprehension as a way to perform a simple for loop in a single line.
Example for adding "pancake" to the end of each string
```
fruits = ['banana', 'strawberry', 'apple']
pancake_types = []
for fruit in fruits:
    pancakes_types.append(fruit + " pancakes")

# with list comprehension
pancake_types_v2 = [fruit + " pancakes" for fruit in fruits]
```

Both result in pancake_types = ['banana pancakes', 'strawberry pancakes', 'apple pancakes'] but the list comprehension is much cleaner, shorter, and doesn't require initializing the list

Lastly, it should also be noted that list comprehension is faster than spelling out the for loop following by the steps.

2024-03-23 17:57 UTC, mcdaly commented on ShutTheBox.py
> +  if 7 not in nums and 8 not in nums and 9 not in nums:
On top of manipulating data within the list comprehension, you can run almost any type of function code here such as mathematical operations, functions, and comparisons.
For what I am asking out of you, the comparison would be the important part to happen for each number (7, 8, 9) of interest.

To summarize how to code up the list comprehension:
new_variable = [<code to execute in for loop> for <cur_value> in <list_of_values>]